name: Laravel CI/CD Pipeline

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the build environment

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up PHP with required extensions
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Update if your Laravel version uses a different PHP version
        extensions: mbstring, intl, mysql, zip

    # Step 3: Cache composer dependencies
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    # Step 4: Install dependencies
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Step 5: Run Laravel tests
    - name: Run tests
      run: php artisan test
